#!/usr/bin/env bash
# run as root
# echo
# echo "  ---%%%%%%%%%%%%%%%%%%%%%%%%%%---"
# echo "----%%%%% SET VARIABLES %%%%%----"
# echo "  ---%%%%%%%%%%%%%%%%%%%%%%%%%%---"
# echo

# set -x
export SRC_HOME="/home/histograph/src"
export DEV_HOME="/home/vagrant/src"
export UPLOADS_DIR="/uploads"
export NEO_PLUGIN_DIR="/var/lib/neo4j/plugins"
export RUN_DIR="/var/run/histograph"
export LOG_DIR="/var/log/histograph"

export MYUSER=histograph

export APIBASEPORT=3000
# export BASEHOST=localhost

if [ "${1} " != " " ]
then
  export APIBASEHOST="api.${1}"
else
  export APIBASEHOST="api.histograph.local"
fi

# export APIBASEURL="http://${APIBASEHOST}:${APIBASEPORT}"
export APIBASEURL="http://${APIBASEHOST}:${APIBASEPORT}"

export MY_BRANCH="puppetdeploy"
export MY_TAG=""
# export MY_TAG="v0.5.1"

export NPM_INSTALL="npm prune && npm install 1>/dev/null"

# export DATA_REPOSITORIES="bag bag-geonames-tgn cshapes geonames geonames-tgn nwb tgn whosonfirst"
# export DATA_REPOSITORIES="geonames nwb tgn whosonfirst"
export DATA_REPOSITORIES="geonames tgn whosonfirst"
export EL_DATA_REPOSITORIES="Departementen atlas-verstedelijking gemeentegeschiedenis kloeke poorterboeken voc-opvarenden carnaval ilvb pleiades verdwenen-dorpen"

export PAGE_SIZE=1000
export SHARD_NR=1
export REPLICA_NR=0

if [ -d ${DEV_HOME} ]
then
  # we are in developer mode, change variables
  SRC_HOME="${DEV_HOME}"
  MYUSER=vagrant
fi


install_service()
{

FOREVER_CONFIG="${SRC_HOME}/${MY_MODULE}.forever.json"

echo "${SRC_HOME}/${MY_MODULE}.forever.json"

cat > ${FOREVER_CONFIG} << FOREVER
{
    "uid": "${MY_MODULE}",
    "append": true,
    "watch": false,
    "script": "index.js",
    "sourceDir": "${SRC_HOME}/${MY_MODULE}",
    "pidFile": "${RUN_DIR}/${MY_MODULE}.pid",
    "logFile": "${LOG_DIR}/${MY_MODULE}.log",
    "args": ["--config", "${SRC_HOME}/config.yaml"]
}
FOREVER

chown ${MYUSER}:${MYUSER} ${FOREVER_CONFIG}

rm -rf /etc/init.d/histograph-${MY_MODULE}

cat > /etc/init.d/histograph-${MY_MODULE} << INITD
#!/bin/bash
### BEGIN INIT INFO
# If you wish the Daemon to be lauched at boot / stopped at shutdown :
#
#    On Debian-based distributions:
#      INSTALL : update-rc.d scriptname defaults
#      (UNINSTALL : update-rc.d -f  scriptname remove)
#
#    On RedHat-based distributions (CentOS, OpenSUSE...):
#      INSTALL : chkconfig --level 35 scriptname on
#      (UNINSTALL : chkconfig --level 35 scriptname off)
#
# chkconfig:         2345 90 60
# Provides:          ${SRC_HOME}/${MY_MODULE}/index.js
# Required-Start:    \$remote_fs \$syslog
# Required-Stop:     \$remote_fs \$syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Histograph ${MY_MODULE}
# Description:       histograph-${MY_MODULE}
### END INIT INFO

FOREVER_CONFIG="${FOREVER_CONFIG}"
FOREVER_UID=${MY_MODULE}
FOREVER_USER=${MYUSER}

case "\$1" in
    start)
        su "\$FOREVER_USER" -c "NODE_ENV=production forever start --uid \$FOREVER_UID \$FOREVER_CONFIG"
        RETVAL=\$?
        ;;
    stop)
        su "\$FOREVER_USER" -c "NODE_ENV=production forever stop \$FOREVER_UID"
        RETVAL=\$?
        ;;
    restart)
        su "\$FOREVER_USER" -c "NODE_ENV=production forever restart \$FOREVER_UID"
        RETVAL=\$?
        ;;
    status)
        su "\$FOREVER_USER" -c "forever list"
        RETVAL=\$?
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit \$RETVAL
INITD

# start on startup
chmod +x /etc/init.d/histograph-${MY_MODULE}
update-rc.d histograph-${MY_MODULE} defaults

service histograph-${MY_MODULE} restart
service histograph-${MY_MODULE} status

}

install_code()
{
  cd ${SRC_HOME}

  if [ "${MY_DEST} " == " " ]
  then
    MY_DEST="${MY_MODULE}"
  fi

  if [ ! -d ${SRC_HOME}/${MY_MODULE} ]
  then
    # clone master branch
    sudo su $MYUSER -c "git clone ${MY_REPO}/${MY_MODULE} ${MY_DEST}"
    if [ ! "${MY_BRANCH} " == " " ]
    then
      sudo su $MYUSER -c "git  -C ${SRC_HOME}/${MY_DEST}/ checkout ${MY_BRANCH}"
    elif [ ! "${MY_TAG} " == " " ]
    then
      sudo su $MYUSER -c "git  -C ${SRC_HOME}/${MY_DEST}/ checkout tags/${MY_TAG}"
    fi
  else
    sudo su $MYUSER -c "git -C ${SRC_HOME}/${MY_DEST}/ pull"
  fi

  if [ "${MY_MODULE}" != "neo4j-plugin" ]
  then
    # install node dependencies
    cd ${SRC_HOME}/${MY_MODULE}
    sudo su $MYUSER -c "${NPM_INSTALL}"
  fi
}

install_data()
{
  export MY_MODULE=data
  export MY_REPO="https://github.com/histograph"

  install_code

  export MY_MODULE=data
  export MY_REPO="https://github.com/erfgoed-en-locatie"
  export MY_DEST=e_l_data

  install_code

}


# set +x
